### ISSUE TITLE
Check for SPDX-valid license name

### ISSUE THREAD

**Issue by dsheets** [ocaml-opam/Camelus#5]
This could potentially go in `opam lint` but it's dependent on an external data source that can change and should be tracked and may represent repository policy rather than a data type constraint.

Related to ocaml/opam#2224.

**Comment by dsheets** [comment]
Checking for the presence of a `license` field *at all* would be a good start toward this per-repository policy.

**Comment by kit-ty-kate** [comment]
Camelus was retired some years ago but in any case opam >= 2.2.0 now checks for the presence of the `license` field and its SPDX-compliance (since opam >= 2.1.0) and is thus already done as part of the regular lint check in opam-repository.
